
Assignmnet no 1

Name: Sarthak Zunjure

Roll No: 03

PRN : 1252090003

1. Import Required Libraries

In [ ]:
import pandas as pd
import numpy as np

2. Create Dataset and DataFrame

In [ ]:
import pandas as pd
import numpy as np
data = {
"Student_ID": [10, 20, 30, 40, 50],
"Name": ["Sarthak", "Abhishek", "Shaurya", "Atharav", "Rushabh"],
"Age": [21, 22, np.nan, 21, 24],
"Gender": ["M", "M", "M", "M", "M"],
"Department": ["CSE-AI", "CSE", "CSE-AI", "AIDS", "AIML"],
"Marks": [85, 78, np.nan, 90, 0],
"Attendance": [92, 99, 95, 95, 0],
"Internship": ["Yes", "No", "Yes", "Yes", "No"]
}
df = pd.DataFrame(data)
df

   Student_ID      Name   Age Gender Department  Marks  Attendance Internship
0          10   Sarthak  21.0      M     CSE-AI   85.0          92        Yes
1          20  Abhishek  22.0      M        CSE   78.0          99         No
2          30   Shaurya   NaN      M     CSE-AI    NaN          95        Yes
3          40   Atharav  21.0      M       AIDS   90.0          95        Yes
4          50   Rushabh  24.0      M       AIML    0.0           0         No

3. Finding Shape of DataFrame

In [ ]:
print(df.shape)

(5, 8)

4. Finding Missing Values in Each Column

In [ ]:
print(df.isnull().sum())

Student_ID    0
Name          0
Age           1
Gender        0
Department    0
Marks         1
Attendance    0
Internship    0
dtype: int64

5. Fetching Data Types of Each Column

In [ ]:
print(df.dtypes)

Student_ID      int64
Name           object
Age           float64
Gender         object
Department     object
Marks         float64
Attendance      int64
Internship     object
dtype: object

6. Counting Number of Zero Values

In [ ]:
print((df == 0).sum())

Student_ID    0
Name          0
Age           0
Gender        0
Department    0
Marks         1
Attendance    1
Internship    0
dtype: int64

7. Selecting First 3 Rows from Dataset

In [ ]:
print(df.loc[:2])

   Student_ID      Name   Age Gender Department  Marks  Attendance Internship
0          10   Sarthak  21.0      M     CSE-AI   85.0          92        Yes
1          20  Abhishek  22.0      M        CSE   78.0          99         No
2          30   Shaurya   NaN      M     CSE-AI    NaN          95        Yes

8. Selecting Name and Marks Columns

In [ ]:
print(df[["Name", "Marks"]])

       Name  Marks
0   Sarthak   85.0
1  Abhishek   78.0
2   Shaurya    NaN
3   Atharav   90.0
4   Rushabh    0.0

9. Sorting by Marks

In [ ]:
print(df.sort_values(by="Marks"))

   Student_ID      Name   Age Gender Department  Marks  Attendance Internship
4          50   Rushabh  24.0      M       AIML    0.0           0         No
1          20  Abhishek  22.0      M        CSE   78.0          99         No
0          10   Sarthak  21.0      M     CSE-AI   85.0          92        Yes
3          40   Atharav  21.0      M       AIDS   90.0          95        Yes
2          30   Shaurya   NaN      M     CSE-AI    NaN          95        Yes

10. Describe Attributes of Data

In [ ]:
print(df.describe(include="all"))

        Student_ID     Name        Age Gender Department      Marks  \
count     5.000000        5   4.000000      5          5   4.000000
unique         NaN        5        NaN      1          4        NaN
top            NaN  Sarthak        NaN      M     CSE-AI        NaN
freq           NaN        1        NaN      5          2        NaN
mean     30.000000      NaN  22.000000    NaN        NaN  63.250000
std      15.811388      NaN   1.414214    NaN        NaN  42.452915
min      10.000000      NaN  21.000000    NaN        NaN   0.000000
25%      20.000000      NaN  21.000000    NaN        NaN  58.500000
50%      30.000000      NaN  21.500000    NaN        NaN  81.500000
75%      40.000000      NaN  22.500000    NaN        NaN  86.250000
max      50.000000      NaN  24.000000    NaN        NaN  90.000000

        Attendance Internship
count     5.000000          5
unique         NaN          2
top            NaN        Yes
freq           NaN          3
mean     76.200000        NaN
std      42.669661        NaN
min       0.000000        NaN
25%      92.000000        NaN
50%      95.000000        NaN
75%      95.000000        NaN
max      99.000000        NaN

11. Rechecking Data Types and Dataset Information

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  5 non-null      int64
 1   Name        5 non-null      object
 2   Age         4 non-null      float64
 3   Gender      5 non-null      object
 4   Department  5 non-null      object
 5   Marks       4 non-null      float64
 6   Attendance  5 non-null      int64
 7   Internship  5 non-null      object
dtypes: float64(2), int64(2), object(4)
memory usage: 452.0+ bytes
None

12. Counting Unique Values in Each Column

In [ ]:
print(df.nunique())

Student_ID    5
Name          5
Age           3
Gender        1
Department    4
Marks         4
Attendance    4
Internship    2
dtype: int64

13. Fetching Column Names

In [ ]:
print(df.columns)

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'Marks',
       'Attendance', 'Internship'],
      dtype='object')

14. Converting Data Types

In [ ]:
df["Student_ID"] = df["Student_ID"].astype("int16")
df["Age"] = df["Age"].astype("float16")
df["Marks"] = df["Marks"].astype("float16")
df["Attendance"] = df["Attendance"].astype("int16")
print("Data Types After Converting:")
print(df.dtypes)

Data Types After Converting:
Student_ID      int16
Name           object
Age           float16
Gender         object
Department     object
Marks         float16
Attendance      int16
Internship     object
dtype: object

Read data from different fromats (CSV, XLS)

In [ ]:
df_csv = pd.read_csv("NY-House-Dataset.csv")
print(df_csv.head())

                                         BROKERTITLE                TYPE  \
0        Brokered by Douglas Elliman  -111 Fifth Ave      Condo for sale
1                                Brokered by Serhant      Condo for sale
2                             Brokered by Sowae Corp      House for sale
3                                Brokered by COMPASS      Condo for sale
4  Brokered by Sotheby's International Realty - E...  Townhouse for sale

       PRICE  BEDS       BATH  PROPERTYSQFT  \
0     315000     2   2.000000        1400.0
1  195000000     7  10.000000       17545.0
2     260000     4   2.000000        2015.0
3      69000     3   1.000000         445.0
4   55000000     7   2.373861       14175.0

                                             ADDRESS                    STATE  \
0                               2 E 55th St Unit 803       New York, NY 10022
1  Central Park Tower Penthouse-217 W 57th New Yo...       New York, NY 10019
2                                   620 Sinclair Ave  Staten Island, NY 10312
3                            2 E 55th St Unit 908W33      Manhattan, NY 10022
4                                        5 E 64th St       New York, NY 10065

                                        MAIN_ADDRESS  \
0             2 E 55th St Unit 803New York, NY 10022
1  Central Park Tower Penthouse-217 W 57th New Yo...
2            620 Sinclair AveStaten Island, NY 10312
3         2 E 55th St Unit 908W33Manhattan, NY 10022
4                      5 E 64th StNew York, NY 10065

  ADMINISTRATIVE_AREA_LEVEL_2  LOCALITY      SUBLOCALITY       STREET_NAME  \
0             New York County  New York        Manhattan  East 55th Street
1               United States  New York  New York County          New York
2               United States  New York  Richmond County     Staten Island
3               United States  New York  New York County          New York
4               United States  New York  New York County          New York

          LONG_NAME                                  FORMATTED_ADDRESS  \
0   Regis Residence  Regis Residence, 2 E 55th St #803, New York, N...
1  West 57th Street             217 W 57th St, New York, NY 10019, USA
2   Sinclair Avenue     620 Sinclair Ave, Staten Island, NY 10312, USA
3  East 55th Street               2 E 55th St, New York, NY 10022, USA
4  East 64th Street               5 E 64th St, New York, NY 10065, USA

    LATITUDE  LONGITUDE
0  40.761255 -73.974483
1  40.766393 -73.980991
2  40.541805 -74.196109
3  40.761398 -73.974613
4  40.767224 -73.969856

Find Shape of Data

In [ ]:
print(df_csv.shape)

(4801, 17)

Find Missing Values

In [ ]:
df_csv.isnull().sum()

BROKERTITLE                    0
TYPE                           0
PRICE                          0
BEDS                           0
BATH                           0
PROPERTYSQFT                   0
ADDRESS                        0
STATE                          0
MAIN_ADDRESS                   0
ADMINISTRATIVE_AREA_LEVEL_2    0
LOCALITY                       0
SUBLOCALITY                    0
STREET_NAME                    0
LONG_NAME                      0
FORMATTED_ADDRESS              0
LATITUDE                       0
LONGITUDE                      0
dtype: int64

Data types

In [ ]:
df_csv.dtypes

BROKERTITLE                     object
TYPE                            object
PRICE                            int64
BEDS                             int64
BATH                           float64
PROPERTYSQFT                   float64
ADDRESS                         object
STATE                           object
MAIN_ADDRESS                    object
ADMINISTRATIVE_AREA_LEVEL_2     object
LOCALITY                        object
SUBLOCALITY                     object
STREET_NAME                     object
LONG_NAME                       object
FORMATTED_ADDRESS               object
LATITUDE                       float64
LONGITUDE                      float64
dtype: object

Find Zero values

In [ ]:
(df_csv.select_dtypes(include=["number"]) == 0).sum()

PRICE           0
BEDS            0
BATH            3
PROPERTYSQFT    0
LATITUDE        0
LONGITUDE       0
dtype: int64

Indexing & selecting

Single column:

In [ ]:
df_csv["PRICE"]

0          315000
1       195000000
2          260000
3           69000
4        55000000
          ...
4796       599000
4797       245000
4798      1275000
4799       598125
4800       349000
Name: PRICE, Length: 4801, dtype: int64

Multiple columns:

In [ ]:
df_csv[["PRICE", "BEDS", "BATH"]]

          PRICE  BEDS       BATH
0        315000     2   2.000000
1     195000000     7  10.000000
2        260000     4   2.000000
3         69000     3   1.000000
4      55000000     7   2.373861
...         ...   ...        ...
4796     599000     1   1.000000
4797     245000     1   1.000000
4798    1275000     1   1.000000
4799     598125     2   1.000000
4800     349000     1   1.000000

[4801 rows x 3 columns]

First 5 rows:

In [ ]:
df_csv.head()

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,SUBLOCALITY,STREET_NAME,LONG_NAME,FORMATTED_ADDRESS,LATITUDE,LONGITUDE
0,Brokered by Douglas Elliman -111 Fifth Ave,Condo for sale,315000,2,2.000000,1400.0,2 E 55th St Unit 803,"New York, NY 10022","2 E 55th St Unit 803New York, NY 10022",New York County,New York,Manhattan,East 55th Street,Regis Residence,"Regis Residence, 2 E 55th St #803, New York, N...",40.761255,-73.974483
1,Brokered by Serhant,Condo for sale,195000000,7,10.000000,17545.0,Central Park Tower Penthouse-217 W 57th New Yo...,"New York, NY 10019",Central Park Tower Penthouse-217 W 57th New Yo...,United States,New York,New York County,New York,West 57th Street,"217 W 57th St, New York, NY 10019, USA",40.766393,-73.980991
2,Brokered by Sowae Corp,House for sale,260000,4,2.000000,2015.0,620 Sinclair Ave,"Staten Island, NY 10312","620 Sinclair AveStaten Island, NY 10312",United States,New York,Richmond County,Staten Island,Sinclair Avenue,"620 Sinclair Ave, Staten Island, NY 10312, USA",40.541805,-74.196109
3,Brokered by COMPASS,Condo for sale,69000,3,1.000000,445.0,2 E 55th St Unit 908W33,"Manhattan, NY 10022","2 E 55th St Unit 908W33Manhattan, NY 10022",United States,New York,New York County,New York,East 55th Street,"2 E 55th St, New York, NY 10022, USA",40.761398,-73.974613
4,Brokered by Sotheby's International Realty - E...,Townhouse for sale,55000000,7,2.373861,14175.0,5 E 64th St,"New York, NY 10065","5 E 64th StNew York, NY 10065",United States,New York,New York County,New York,East 64th Street,"5 E 64th St, New York, NY 10065, USA",40.767224,-73.969856

Rows with condition:

In [ ]:
df_csv[df_csv["PRICE"] > 2000]

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,SUBLOCALITY,STREET_NAME,LONG_NAME,FORMATTED_ADDRESS,LATITUDE,LONGITUDE
0,Brokered by Douglas Elliman -111 Fifth Ave,Condo for sale,315000,2,2.000000,1400.000000,2 E 55th St Unit 803,"New York, NY 10022","2 E 55th St Unit 803New York, NY 10022",New York County,New York,Manhattan,East 55th Street,Regis Residence,"Regis Residence, 2 E 55th St #803, New York, N...",40.761255,-73.974483
1,Brokered by Serhant,Condo for sale,195000000,7,10.000000,17545.000000,Central Park Tower Penthouse-217 W 57th New Yo...,"New York, NY 10019",Central Park Tower Penthouse-217 W 57th New Yo...,United States,New York,New York County,New York,West 57th Street,"217 W 57th St, New York, NY 10019, USA",40.766393,-73.980991
2,Brokered by Sowae Corp,House for sale,260000,4,2.000000,2015.000000,620 Sinclair Ave,"Staten Island, NY 10312","620 Sinclair AveStaten Island, NY 10312",United States,New York,Richmond County,Staten Island,Sinclair Avenue,"620 Sinclair Ave, Staten Island, NY 10312, USA",40.541805,-74.196109
3,Brokered by COMPASS,Condo for sale,69000,3,1.000000,445.000000,2 E 55th St Unit 908W33,"Manhattan, NY 10022","2 E 55th St Unit 908W33Manhattan, NY 10022",United States,New York,New York County,New York,East 55th Street,"2 E 55th St, New York, NY 10022, USA",40.761398,-73.974613
4,Brokered by Sotheby's International Realty - E...,Townhouse for sale,55000000,7,2.373861,14175.000000,5 E 64th St,"New York, NY 10065","5 E 64th StNew York, NY 10065",United States,New York,New York County,New York,East 64th Street,"5 E 64th St, New York, NY 10065, USA",40.767224,-73.969856
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,Brokered by COMPASS,Co-op for sale,599000,1,1.000000,2184.207862,222 E 80th St Apt 3A,"Manhattan, NY 10075","222 E 80th St Apt 3AManhattan, NY 10075",New York,New York County,New York,Manhattan,222,"222 E 80th St #3a, New York, NY 10075, USA",40.774350,-73.955879
4797,Brokered by Mjr Real Estate Llc,Co-op for sale,245000,1,1.000000,2184.207862,97-40 62 Dr Unit Lg,"Rego Park, NY 11374","97-40 62 Dr Unit LgRego Park, NY 11374",United States,New York,Queens County,Queens,62nd Drive,"97-40 62nd Dr, Rego Park, NY 11374, USA",40.732538,-73.860152
4798,Brokered by Douglas Elliman - 575 Madison Ave,Co-op for sale,1275000,1,1.000000,2184.207862,427 W 21st St Unit Garden,"New York, NY 10011","427 W 21st St Unit GardenNew York, NY 10011",United States,New York,New York County,New York,West 21st Street,"427 W 21st St, New York, NY 10011, USA",40.745882,-74.003398
4799,Brokered by E Realty International Corp,Condo for sale,598125,2,1.000000,655.000000,91-23 Corona Ave Unit 4G,"Elmhurst, NY 11373","91-23 Corona Ave Unit 4GElmhurst, NY 11373",New York,Queens County,Queens,Flushing,91-23,"91-23 Corona Ave. #4b, Flushing, NY 11373, USA",40.742770,-73.872752
4800,Brokered by Nyc Realty Brokers Llc,Co-op for sale,349000,1,1.000000,750.000000,460 Neptune Ave Apt 14O,"Brooklyn, NY 11224","460 Neptune Ave Apt 14OBrooklyn, NY 11224",New York,Kings County,Brooklyn,Coney Island,460,"460 Neptune Ave #14a, Brooklyn, NY 11224, USA",40.579147,-73.970949

Sorting

Ascending

In [ ]:
df_csv.sort_values(by="PRICE")

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,SUBLOCALITY,STREET_NAME,LONG_NAME,FORMATTED_ADDRESS,LATITUDE,LONGITUDE
317,Brokered by Living NY - Main Office,For sale,2494,2,1.000000,2184.207862,635 W 170th St Apt 4F,"New York, NY 10032","635 W 170th St Apt 4FNew York, NY 10032",New York,New York County,New York,Manhattan,635,"635 W 170th St #4f, New York, NY 10032, USA",40.843406,-73.940795
310,Brokered by Living NY - Main Office,For sale,3225,3,1.000000,2184.207862,635 W 170th St Apt 2C,"New York, NY 10032","635 W 170th St Apt 2CNew York, NY 10032",New York,New York County,New York,Manhattan,635,"635 W 170th St #2c, New York, NY 10032, USA",40.843406,-73.940795
360,Brokered by Century 21 Realty First,Land for sale,5800,3,2.373861,2184.207862,4515 Avenue N Lot 5,"Brooklyn, NY 11234","4515 Avenue N Lot 5Brooklyn, NY 11234",New York,Kings County,Brooklyn,Flatlands,4515,"4515 Avenue N #5, Brooklyn, NY 11234, USA",40.618915,-73.931211
463,Brokered by Morris Park Realty Group,Co-op for sale,49500,3,2.373861,800.000000,150 City Island Ave Unit E3,"Bronx, NY 10464","150 City Island Ave Unit E3Bronx, NY 10464",New York,Bronx County,The Bronx,City Island,150,"150 City Island Ave #3e, Bronx, NY 10464, USA",40.843284,-73.784603
979,Brokered by COMPASS,Condo for sale,60000,3,1.000000,445.000000,2 E 55th St Unit 809W35,"Manhattan, NY 10022","2 E 55th St Unit 809W35Manhattan, NY 10022",New York,New York County,New York,Manhattan,2,"2 E 55th St 809 35, New York, NY 10022, USA",40.761398,-73.974613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,Brokered by Douglas Elliman - 575 Madison Ave,House for sale,56000000,11,10.000000,24000.000000,9 W 54th St,"New York, NY 10019","9 W 54th StNew York, NY 10019",United States,New York,New York County,New York,West 54th Street,"9 W 54th St, New York, NY 10019, USA",40.761600,-73.976191
1075,Brokered by COMPASS,Co-op for sale,60000000,8,8.000000,2184.207862,960 5th Ave Unit 12,"Manhattan, NY 10075","960 5th Ave Unit 12Manhattan, NY 10075",New York,New York County,New York,Manhattan,960,"960 5th Ave #12, New York, NY 10075, USA",40.775642,-73.964247
69,Brokered by Sotheby's International Realty - E...,Townhouse for sale,65000000,3,2.373861,15200.000000,4 E 79th St,"New York, NY 10075","4 E 79th StNew York, NY 10075",United States,New York,New York County,New York,East 79th Street,"4 E 79th St, New York, NY 10075, USA",40.776561,-73.963317
1,Brokered by Serhant,Condo for sale,195000000,7,10.000000,17545.000000,Central Park Tower Penthouse-217 W 57th New Yo...,"New York, NY 10019",Central Park Tower Penthouse-217 W 57th New Yo...,United States,New York,New York County,New York,West 57th Street,"217 W 57th St, New York, NY 10019, USA",40.766393,-73.980991
304,Brokered by ANNE LOPA REAL ESTATE,House for sale,2147483647,7,6.000000,10000.000000,6659-6675 Amboy Rd,"New York, NY 10309","6659-6675 Amboy RdNew York, NY 10309",United States,New York,Richmond County,Staten Island,Amboy Road,"6659 Amboy Rd, Staten Island, NY 10309, USA",40.518484,-74.224418

Descending:

In [ ]:
df_csv.sort_values(by="PRICE", ascending=False)

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,SUBLOCALITY,STREET_NAME,LONG_NAME,FORMATTED_ADDRESS,LATITUDE,LONGITUDE
304,Brokered by ANNE LOPA REAL ESTATE,House for sale,2147483647,7,6.000000,10000.000000,6659-6675 Amboy Rd,"New York, NY 10309","6659-6675 Amboy RdNew York, NY 10309",United States,New York,Richmond County,Staten Island,Amboy Road,"6659 Amboy Rd, Staten Island, NY 10309, USA",40.518484,-74.224418
1,Brokered by Serhant,Condo for sale,195000000,7,10.000000,17545.000000,Central Park Tower Penthouse-217 W 57th New Yo...,"New York, NY 10019",Central Park Tower Penthouse-217 W 57th New Yo...,United States,New York,New York County,New York,West 57th Street,"217 W 57th St, New York, NY 10019, USA",40.766393,-73.980991
69,Brokered by Sotheby's International Realty - E...,Townhouse for sale,65000000,3,2.373861,15200.000000,4 E 79th St,"New York, NY 10075","4 E 79th StNew York, NY 10075",United States,New York,New York County,New York,East 79th Street,"4 E 79th St, New York, NY 10075, USA",40.776561,-73.963317
1075,Brokered by COMPASS,Co-op for sale,60000000,8,8.000000,2184.207862,960 5th Ave Unit 12,"Manhattan, NY 10075","960 5th Ave Unit 12Manhattan, NY 10075",New York,New York County,New York,Manhattan,960,"960 5th Ave #12, New York, NY 10075, USA",40.775642,-73.964247
141,Brokered by Douglas Elliman - 575 Madison Ave,House for sale,56000000,11,10.000000,24000.000000,9 W 54th St,"New York, NY 10019","9 W 54th StNew York, NY 10019",United States,New York,New York County,New York,West 54th Street,"9 W 54th St, New York, NY 10019, USA",40.761600,-73.976191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,Brokered by COMPASS,Condo for sale,60000,3,1.000000,445.000000,2 E 55th St Unit 809W35,"Manhattan, NY 10022","2 E 55th St Unit 809W35Manhattan, NY 10022",New York,New York County,New York,Manhattan,2,"2 E 55th St 809 35, New York, NY 10022, USA",40.761398,-73.974613
463,Brokered by Morris Park Realty Group,Co-op for sale,49500,3,2.373861,800.000000,150 City Island Ave Unit E3,"Bronx, NY 10464","150 City Island Ave Unit E3Bronx, NY 10464",New York,Bronx County,The Bronx,City Island,150,"150 City Island Ave #3e, Bronx, NY 10464, USA",40.843284,-73.784603
360,Brokered by Century 21 Realty First,Land for sale,5800,3,2.373861,2184.207862,4515 Avenue N Lot 5,"Brooklyn, NY 11234","4515 Avenue N Lot 5Brooklyn, NY 11234",New York,Kings County,Brooklyn,Flatlands,4515,"4515 Avenue N #5, Brooklyn, NY 11234, USA",40.618915,-73.931211
310,Brokered by Living NY - Main Office,For sale,3225,3,1.000000,2184.207862,635 W 170th St Apt 2C,"New York, NY 10032","635 W 170th St Apt 2CNew York, NY 10032",New York,New York County,New York,Manhattan,635,"635 W 170th St #2c, New York, NY 10032, USA",40.843406,-73.940795
317,Brokered by Living NY - Main Office,For sale,2494,2,1.000000,2184.207862,635 W 170th St Apt 4F,"New York, NY 10032","635 W 170th St Apt 4FNew York, NY 10032",New York,New York County,New York,Manhattan,635,"635 W 170th St #4f, New York, NY 10032, USA",40.843406,-73.940795

Describe attributes

In [ ]:
df_csv.describe()

,PRICE,BEDS,BATH,PROPERTYSQFT,LATITUDE,LONGITUDE
count,4.801000e+03,4801.000000,4801.000000,4801.000000,4801.000000,4801.000000
mean,2.356940e+06,3.356801,2.373861,2184.207862,40.714227,-73.941601
std,3.135525e+07,2.602315,1.946962,2377.140894,0.087676,0.101082
min,2.494000e+03,1.000000,0.000000,230.000000,40.499546,-74.253033
25%,4.990000e+05,2.000000,1.000000,1200.000000,40.639375,-73.987143
50%,8.250000e+05,3.000000,2.000000,2184.207862,40.726749,-73.949189
75%,1.495000e+06,4.000000,3.000000,2184.207862,40.771923,-73.870638
max,2.147484e+09,50.000000,50.000000,65535.000000,40.912729,-73.702450

All columns:

In [ ]:
df_csv.describe(include="all")

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,SUBLOCALITY,STREET_NAME,LONG_NAME,FORMATTED_ADDRESS,LATITUDE,LONGITUDE
count,4801,4801,4.801000e+03,4801.000000,4801.000000,4801.000000,4801,4801,4801,4801,4801,4801,4801,4801,4801,4801.000000,4801.000000
unique,1036,13,NaN,NaN,NaN,NaN,4582,308,4583,29,11,21,174,2731,4550,NaN,NaN
top,Brokered by COMPASS,Co-op for sale,NaN,NaN,NaN,NaN,856 Washington Ave Apt 6C,"Brooklyn, NY 11235","856 Washington Ave Apt 6CBrooklyn, NY 11238",United States,New York,New York,Manhattan,2,"61-20 Grand Central Pkwy, Forest Hills, NY 113...",NaN,NaN
freq,456,1450,NaN,NaN,NaN,NaN,3,102,3,2484,2505,1016,979,20,4,NaN,NaN
mean,NaN,NaN,2.356940e+06,3.356801,2.373861,2184.207862,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.714227,-73.941601
std,NaN,NaN,3.135525e+07,2.602315,1.946962,2377.140894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.087676,0.101082
min,NaN,NaN,2.494000e+03,1.000000,0.000000,230.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.499546,-74.253033
25%,NaN,NaN,4.990000e+05,2.000000,1.000000,1200.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.639375,-73.987143
50%,NaN,NaN,8.250000e+05,3.000000,2.000000,2184.207862,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.726749,-73.949189
75%,NaN,NaN,1.495000e+06,4.000000,3.000000,2184.207862,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.771923,-73.870638
max,NaN,NaN,2.147484e+09,50.000000,50.000000,65535.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.912729,-73.702450

Dataset info

In [ ]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4801 entries, 0 to 4800
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   BROKERTITLE                  4801 non-null   object
 1   TYPE                         4801 non-null   object
 2   PRICE                        4801 non-null   int64
 3   BEDS                         4801 non-null   int64
 4   BATH                         4801 non-null   float64
 5   PROPERTYSQFT                 4801 non-null   float64
 6   ADDRESS                      4801 non-null   object
 7   STATE                        4801 non-null   object
 8   MAIN_ADDRESS                 4801 non-null   object
 9   ADMINISTRATIVE_AREA_LEVEL_2  4801 non-null   object
 10  LOCALITY                     4801 non-null   object
 11  SUBLOCALITY                  4801 non-null   object
 12  STREET_NAME                  4801 non-null   object
 13  LONG_NAME                    4801 non-null   object
 14  FORMATTED_ADDRESS            4801 non-null   object
 15  LATITUDE                     4801 non-null   float64
 16  LONGITUDE                    4801 non-null   float64
dtypes: float64(4), int64(2), object(11)
memory usage: 637.8+ KB

Counting unique values

In [ ]:
df_csv.nunique()

BROKERTITLE                    1036
TYPE                             13
PRICE                          1274
BEDS                             27
BATH                             22
PROPERTYSQFT                   1445
ADDRESS                        4582
STATE                           308
MAIN_ADDRESS                   4583
ADMINISTRATIVE_AREA_LEVEL_2      29
LOCALITY                         11
SUBLOCALITY                      21
STREET_NAME                     174
LONG_NAME                      2731
FORMATTED_ADDRESS              4550
LATITUDE                       4196
LONGITUDE                      4118
dtype: int64

Column names

In [ ]:
df_csv.columns

Index(['BROKERTITLE', 'TYPE', 'PRICE', 'BEDS', 'BATH', 'PROPERTYSQFT',
       'ADDRESS', 'STATE', 'MAIN_ADDRESS', 'ADMINISTRATIVE_AREA_LEVEL_2',
       'LOCALITY', 'SUBLOCALITY', 'STREET_NAME', 'LONG_NAME',
       'FORMATTED_ADDRESS', 'LATITUDE', 'LONGITUDE'],
      dtype='object')

Datatype conversion

In [ ]:
df_csv["BEDS"] = df_csv["BEDS"].astype("float16")
df_csv["BATH"] = df_csv["BATH"].astype("float16")
df_csv["PRICE"] = df_csv["PRICE"].astype("float32")
print("Data Types After Converting:")
print(df_csv.dtypes)

Data Types After Converting:
BROKERTITLE                     object
TYPE                            object
PRICE                          float32
BEDS                           float16
BATH                           float16
PROPERTYSQFT                   float64
ADDRESS                         object
STATE                           object
MAIN_ADDRESS                    object
ADMINISTRATIVE_AREA_LEVEL_2     object
LOCALITY                        object
SUBLOCALITY                     object
STREET_NAME                     object
LONG_NAME                       object
FORMATTED_ADDRESS               object
LATITUDE                       float64
LONGITUDE                      float64
dtype: object